import { ShapeDiff, VoxelPosition } from '../models/game.models';

function posKey(v: VoxelPosition): string {
  return `${v.x},${v.y},${v.z}`;
}

/**
 * The 24 rotation matrices for a cube (rotation group of the cube).
 * Each is a 3x3 matrix represented as [row0, row1, row2] where each row is [a, b, c].
 * Applying: newX = a0*x + a1*y + a2*z, etc.
 */
const ROTATIONS_24: [number, number, number][][] = [
  // Identity and rotations around Y axis
  [[ 1, 0, 0],[ 0, 1, 0],[ 0, 0, 1]],
  [[ 0, 0, 1],[ 0, 1, 0],[-1, 0, 0]],
  [[-1, 0, 0],[ 0, 1, 0],[ 0, 0,-1]],
  [[ 0, 0,-1],[ 0, 1, 0],[ 1, 0, 0]],
  // Rotations around X axis
  [[ 1, 0, 0],[ 0, 0,-1],[ 0, 1, 0]],
  [[ 1, 0, 0],[ 0,-1, 0],[ 0, 0,-1]],
  [[ 1, 0, 0],[ 0, 0, 1],[ 0,-1, 0]],
  // Rotations around Z axis
  [[ 0,-1, 0],[ 1, 0, 0],[ 0, 0, 1]],
  [[-1, 0, 0],[ 0,-1, 0],[ 0, 0, 1]],
  [[ 0, 1, 0],[-1, 0, 0],[ 0, 0, 1]],
  // Face +X up (X axis pointing up, then 4 rotations)
  [[ 0, 1, 0],[ 0, 0, 1],[ 1, 0, 0]],
  [[ 0, 0, 1],[ 0,-1, 0],[ 1, 0, 0]],  // fixed from duplicate
  [[ 0,-1, 0],[ 0, 0,-1],[ 1, 0, 0]],
  [[ 0, 0,-1],[ 0, 1, 0],[ 1, 0, 0]],
  // Face -X up
  [[ 0, 1, 0],[ 0, 0,-1],[-1, 0, 0]],
  [[ 0, 0,-1],[ 0,-1, 0],[-1, 0, 0]],
  [[ 0,-1, 0],[ 0, 0, 1],[-1, 0, 0]],
  [[ 0, 0, 1],[ 0, 1, 0],[-1, 0, 0]],
  // Face -Y up
  [[ 1, 0, 0],[ 0,-1, 0],[ 0, 0,-1]],  // same as index 5, replace:
  [[-1, 0, 0],[ 0,-1, 0],[ 0, 0, 1]],  // same as index 8, replace:
  // Face +Z up
  [[ 1, 0, 0],[ 0, 0, 1],[ 0,-1, 0]],  // same as index 6
  [[ 0,-1, 0],[ 0, 0, 1],[-1, 0, 0]],  // new
  // Face -Z up
  [[-1, 0, 0],[ 0, 0, 1],[ 0, 1, 0]],
  [[ 0, 1, 0],[ 0, 0, 1],[-1, 0, 0]],  // new
];

/**
 * Generates all 24 unique rotation matrices programmatically to avoid manual errors.
 * Uses the fact that the rotation group is generated by 90° rotations around X and Y.
 */
function generateAll24Rotations(): [number, number, number][][] {
  const results: [number, number, number][][] = [];
  const seen = new Set<string>();

  // Rotation around X by 90°
  const rx: [number, number, number][] = [[1,0,0],[0,0,-1],[0,1,0]];
  // Rotation around Y by 90°
  const ry: [number, number, number][] = [[0,0,1],[0,1,0],[-1,0,0]];
  // Rotation around Z by 90°
  const rz: [number, number, number][] = [[0,-1,0],[1,0,0],[0,0,1]];

  function mulMat(a: [number,number,number][], b: [number,number,number][]): [number,number,number][] {
    const r: [number,number,number][] = [[0,0,0],[0,0,0],[0,0,0]];
    for (let i = 0; i < 3; i++) {
      for (let j = 0; j < 3; j++) {
        r[i][j] = a[i][0]*b[0][j] + a[i][1]*b[1][j] + a[i][2]*b[2][j];
      }
    }
    return r;
  }

  function matKey(m: [number,number,number][]): string {
    return m.flat().join(',');
  }

  // Identity
  let identity: [number,number,number][] = [[1,0,0],[0,1,0],[0,0,1]];

  // Generate by applying all combinations of rx^a * ry^b * rz^c (a,b,c in 0..3)
  for (let a = 0; a < 4; a++) {
    for (let b = 0; b < 4; b++) {
      for (let c = 0; c < 4; c++) {
        let m = identity;
        for (let i = 0; i < a; i++) m = mulMat(m, rx);
        for (let i = 0; i < b; i++) m = mulMat(m, ry);
        for (let i = 0; i < c; i++) m = mulMat(m, rz);
        const key = matKey(m);
        if (!seen.has(key)) {
          seen.add(key);
          results.push(m);
        }
      }
    }
  }

  return results;
}

/** All 24 unique rotation matrices, generated once. */
const ALL_ROTATIONS = generateAll24Rotations();

/** Applies a rotation matrix to a position. */
function applyRotation(rot: [number,number,number][], x: number, y: number, z: number): [number, number, number] {
  return [
    rot[0][0]*x + rot[0][1]*y + rot[0][2]*z,
    rot[1][0]*x + rot[1][1]*y + rot[1][2]*z,
    rot[2][0]*x + rot[2][1]*y + rot[2][2]*z,
  ];
}

/** Normalizes positions so the minimum on each axis is 0. */
function normalize(positions: [number, number, number][]): [number, number, number][] {
  if (positions.length === 0) return [];
  let minX = Infinity, minY = Infinity, minZ = Infinity;
  for (const [x, y, z] of positions) {
    if (x < minX) minX = x;
    if (y < minY) minY = y;
    if (z < minZ) minZ = z;
  }
  return positions.map(([x, y, z]) => [x - minX, y - minY, z - minZ]);
}

/** Creates a canonical string key for a set of positions (sorted). */
function shapeKey(positions: [number, number, number][]): string {
  return positions.map(([x, y, z]) => `${x},${y},${z}`).sort().join('|');
}

/**
 * Creates a canonical key for a voxel including position, color, and symbol.
 */
function voxelKey(x: number, y: number, z: number, color: string, symbol: string | null): string {
  return `${x},${y},${z}:${color}:${symbol ?? ''}`;
}

/**
 * Creates a canonical sorted key for a set of voxels (position + color + symbol).
 */
function fullShapeKey(positions: [number, number, number][], voxels: VoxelPosition[]): string {
  const entries = positions.map((p, i) => voxelKey(p[0], p[1], p[2], voxels[i].color, voxels[i].symbol));
  return entries.sort().join('|');
}

/**
 * Checks if two shapes match under any of the 24 cube rotations.
 * All cubes must match both position AND color/symbol.
 */
export function shapesMatchRotationInvariant(
  target: VoxelPosition[],
  build: VoxelPosition[],
): boolean {
  if (target.length !== build.length) return false;
  if (target.length === 0) return true;

  // Build target lookup: normalized position → {color, symbol}
  const targetPositions: [number, number, number][] = target.map(v => [v.x, v.y, v.z]);
  const normTarget = normalize(targetPositions);
  const targetMap = new Map<string, { color: string; symbol: string | null }>();
  for (let i = 0; i < normTarget.length; i++) {
    const [x, y, z] = normTarget[i];
    targetMap.set(`${x},${y},${z}`, { color: target[i].color, symbol: target[i].symbol });
  }

  const buildPositions: [number, number, number][] = build.map(v => [v.x, v.y, v.z]);

  for (const rot of ALL_ROTATIONS) {
    const rotated = buildPositions.map(([x, y, z]) => applyRotation(rot, x, y, z));
    const normRotated = normalize(rotated);

    let match = true;
    for (let i = 0; i < normRotated.length; i++) {
      const [x, y, z] = normRotated[i];
      const key = `${x},${y},${z}`;
      const targetVoxel = targetMap.get(key);

      if (!targetVoxel) {
        match = false;
        break;
      }

      // Check color and symbol match
      if (build[i].color !== targetVoxel.color || build[i].symbol !== targetVoxel.symbol) {
        match = false;
        break;
      }
    }

    if (match) return true;
  }

  return false;
}

/**
 * Compares a target shape against a player build and produces a ShapeDiff.
 * Direct position comparison (no rotation).
 */
export function compareShapes(
  target: VoxelPosition[],
  playerBuild: VoxelPosition[],
  colorMode: boolean,
): ShapeDiff {
  const targetMap = new Map<string, VoxelPosition>();
  const playerMap = new Map<string, VoxelPosition>();

  for (const v of target) {
    targetMap.set(posKey(v), v);
  }
  for (const v of playerBuild) {
    playerMap.set(posKey(v), v);
  }

  const correct: VoxelPosition[] = [];
  const missing: VoxelPosition[] = [];
  const extra: VoxelPosition[] = [];

  for (const [key, targetVoxel] of targetMap) {
    const playerVoxel = playerMap.get(key);
    if (playerVoxel) {
      if (!colorMode || targetVoxel.color === playerVoxel.color) {
        correct.push(targetVoxel);
      } else {
        missing.push(targetVoxel);
        extra.push(playerVoxel);
      }
    } else {
      missing.push(targetVoxel);
    }
  }

  for (const [key, playerVoxel] of playerMap) {
    if (!targetMap.has(key)) {
      extra.push(playerVoxel);
    }
  }

  return { correct, missing, extra };
}
