export interface GameEntry {
  route: string;
  name: string;
  description: string;
  icon: string;
  label: string;
}

export const GAME_LIST: GameEntry[] = [
  { route: '/nback', name: 'Dual N-Back', label: 'Working memory', description: 'Designed by science. Tested by millions. Conquered by you.', icon: 'assets/icons/nback-icon.png' },
  { route: '/multitask', name: 'Splittention', label: 'Multitasking', description: 'Three tasks, one brain. Let\'s see how long the juggling act lasts.', icon: 'assets/icons/multitask-icon.png' },
  { route: '/mindflow', name: 'MindFlow', label: 'Executive function', description: 'Track positions and movements to the edge of sanity.', icon: 'assets/icons/mindflow-icon.png' },
  { route: '/numbers', name: 'Recallc', label: 'Short-term memory', description: 'You\'re forgetting where you put your keys. Time to fix that.', icon: 'assets/icons/numbers-icon.png' },
  { route: '/phantomlink', name: 'PhantomLink', label: 'Memory updating', description: 'You memorize, we change. Over and over again.', icon: 'assets/icons/phantom-icon.png' },
  // { route: '/synapsort', name: 'SynapSort', label: 'Cognitive flexibility', description: 'The rules just changed. Again. Keep up.', icon: 'assets/icons/synapsort-icon.png' },
  // { route: '/focusforge', name: 'FocusForge', label: 'Selective attention', description: 'It\'s right there. You just can\'t see it. Yet.', icon: 'assets/icons/focusforge-icon.png' },
];

export const TAGLINES: string[] = [
  'IQ doesn\'t stand for "I Quit"',
  'Water your brain as a heavy rain',
  'Let your brain hop on a train',
  'IQ is not optional',
  'If it hurts, it grows',
  'No brain, no gain',
  'Your neurons called. They want a challenge.',
  'Brain day is every day',
  'Start at 120%. Then progressively increase.',
  'Think harder. Then some more.',
  'Mental reps don\'t count unless they hurt',
  'Comfort zone? Never heard of her.',
  'If your brain isn\'t crying, you\'re not trying',
  'Swole mind, zero excuses',
  'Grind the grey matter',
  'Neurons don\'t grow in the shade',
  'Rest day is for your body, not your brain',
  'Cognitive gain or cognitive shame',
  'Train your brain or it trains you',
  'Your IQ won\'t spot itself',
  'Synapses don\'t fire themselves',
  'Think until it burns. Then think more.',
  'Weak focus is a choice',
  'Your prefrontal cortex deserves better',
  'No shortcuts. Only neural pathways.',
  'Flex that frontal lobe',
  'Brains over everything',
  'You vs. your last brain cell. Fight.',
  'Mental gains loading...',
  'Discipline is remembering what your brain forgot',
  'Cry now, think later',
  'Every neuron earned, not given',
  'Your working memory is not working hard enough',
  'Make your short-term memory longer',
  'This is no place for weak minds',
  'Mediocre minds don\'t play here',
  'No pain, no prefrontal gain',
  'Heavier thoughts = Stronger mind',
  'Your neurons are soft. Harden them.',
  'Mental DOMS or mental loss',
  'Weak focus is not tolerated',
  'Synapses don\'t grow from comfort',
  'Your cortex called. You should call back.',
  'Brain gains don\'t come from excuses',
  'Grind until your IQ begs for mercy',
  'Think heavy. Lift heavier thoughts.',
  'Lazy neurons get pruned forever',
  'Make your working memory do overtimes',
  'No reps, no respect from your future self',
  'Feel the burn in your frontal lobe',
  'Cognitive PRs or permanent regression',
  'Your brain\'s been benching feathers',
  'Stop scrolling. Start solving.',
  'Mental atrophy is not a personality trait',
  'If your head isn\'t pounding, you\'re coasting',
  'Neurons hate weak owners',
  'Build the brain or become the background',
  'Make your amygdala play on hard mode',
  'Resting is for corpses, not cortexes',
  'Every missed problem is a missed gain',
  'Train insane or remain the same',
  'Your brain is calling collect from the comfort zone',
  'Flex the frontal or flex the excuses',
  'Sweat your synapses or stay soft',
  'Cognitive failure is not an option',
  'Your IQ is crying for another set',
  'Push past the plateau or perish',
  'Brain dead? Nah, just brain lazy.',
  'No mercy for lazy minds',
  'Forge your mind in the fire of failure',
  'Weak thoughts die in this app',
  'Your brain can do more. Prove it.',
  'Struggle is the syllabus',
  'Brainpower is built, not gifted',
  'Intelligence needs resistance',
  'Hard mode is the warm-up',
  'Make your cortex carry its weight',
  'Rep by rep, thought by thought',
  'Focus is a muscle. Use it.',
  'Rewire your brain with optic cables',
  'Mental weakness is expensive',
  'You are not rich enough to effort being dumb',
  'Train the mind you wish you had',
  'Push until clarity shows up',
  'Thinking under pressure is the point',
  'Tough tasks make tougher minds',
  'Don\'t wish for easy task, wish for strong mind',
  'Strong brains love hard problems',
  'This is where soft thinking ends',
  'To increase your limits you have to reach them first',
  'Mental strength starts where ease ends',
  'Grind now. Glide later.',
  'Brainwork is real work',
  'The easy path grows nothing',
  'Smarter by force',
  'Make difficulty your training partner',
  'Challenge is the nourishment',
  'The mind grows where comfort dies',
  'Progressive overload is the key to growth',
  'Banish weak neurons',
  'Your future brain is watching',
  'You don’t need motivation. You need load.',
  'Diamonds are made under pressure',
  'No friction, no function',
  'Ignite your brain compound effect - now!',
  'The answer is on the other side of effort',
  'Do it for the wrinkle gains',
  'Consider this a hostile takeover of your comfort zone',
  'Make your gray matter less decorative',
  'All your excuse-checks are here-forth declined',
  'Your brain deserves better side quests'
];
